apiVersion: apps/v1
kind: Deployment
metadata:
  name: sword-health-app-prod
spec:
  selector:
    matchLabels:
      app: sword-health-app-prod
  template:
    metadata:
      labels:
        app: sword-health-app-prod
    spec:
      containers:
        - name: sword-health-app-prod
          image: sword-health:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
      volumeMounts:
        - name: sword-health-app-env-prod-vol
          mountPath: /app/resources/.env.prod 
          subPath: .env.prod
      volumes:
        - name: sword-health-app-env-prod-vol
          configMap:
            name: sword-health-app-env-prod
    
      
